mysql:
  image: "dnhsoft/mysql-utf8"
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  container_name: "mysql"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=fuel_db
fuelphp:
  image: hiro511/fuelphp
  container_name: "fuel"
  ports:
   - "80:80"
  volumes:
   - "$PWD/src:/var/www/html/fuel/fuel/app"
  links:
   - "mysql"
